[package]
name = "rt"
version = "0.1.0"
authors = ["Andrey Stoyan <andrey.stoyan.csam@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
png = "0.16.6"
nalgebra = "0.20"
