[package]
name = "rt"
version = "0.1.0"
authors = ["Andrey Stoyan <andrey.stoyan.csam@gmail.com>"]
edition = "2018"

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
nalgebra = "0.20"
approx = "0.3.2"
float-ord = "0.2.0"

[dependencies.image]
path = "../image"
